# Generated by Django 4.2.1 on 2023-05-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_region_street_ad_date_of_creation_ad_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(help_text='Описание объявления', max_length=500),
        ),
        migrations.AlterField(
            model_name='ad',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
