# Generated by Django 4.2.1 on 2023-05-14 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0004_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ad.type'),
            preserve_default=False,
        ),
    ]
