# Generated by Django 4.2.1 on 2023-05-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0007_ad_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='phone_number',
            field=models.CharField(default=1, help_text='Номер телефона', max_length=50),
            preserve_default=False,
        ),
    ]
