# Generated by Django 4.2.1 on 2023-05-16 14:44

import ad.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0008_individual_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=ad.models.get_image_filename),
        ),
    ]
