# Generated by Django 4.2.1 on 2023-05-23 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0009_alter_ad_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_price', models.IntegerField(blank=True, help_text='Предложение новой цены', null=True)),
                ('description', models.TextField(blank=True, help_text='Описание предложения', max_length=200, null=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.ad')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.individual')),
            ],
        ),
    ]
